# SPDX-FileCopyrightText: 2023 Christian Willberg <christian.willberg@dlr.de>, Jan-Timo Hesse <jan-timo.hesse@dlr.de>
#
# SPDX-License-Identifier: BSD-3-Clause

# - id: runtests_julia
#   name: "runtests_julia"
#   entry: pre_commit_hooks/runtests.sh
#   files: '\.(jl|JL)$'
#   verbose: true
#   language: "script"
#   description: "Runs julia tests"
# - id: format_julia
#   name: "format_julia"
#   entry: pre_commit_hooks/format.sh
#   files: '\.(jl|JL)$'
#   verbose: true
#   language: "script"
#   description: "Reformats Julia code"
