# SPDX-FileCopyrightText: 2023 Christian Willberg <christian.willberg@dlr.de>, Jan-Timo Hesse <jan-timo.hesse@dlr.de>
#
# SPDX-License-Identifier: BSD-3-Clause

name: 🚀 Feature request
description: If you have a feature request 💡
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form!
  - type: textarea
    id: what
    attributes:
      label: What are you trying to do and how would you want to do it differently?
      value: "I would like to ..."
    validations:
      required: true
